name: deployment workflow
on:
  push:
    branches: [ master ]
    
jobs:
  deploy_job:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: some command
      uses: SavelevMD/ssh-command-action@master
      with:
        host: 94.250.252.236
        username: stickermark
        key: ${{ secrets.QRB_KEY}}
        port: 22
        script: |
          mkdir is_work
