name: deployment workflow
on:
  push:
    branches: [ master ]
    
jobs:
  deploy_job:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: SSH Command
      uses: D3rHase/ssh-command-action@v0.2.1
      with:
        host: 94.250.252.236
        username: savelevmd
        key: ${{ secrets.QRB_KEY}}
        port: 22
        script: |
          mkdir is_work
